//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentations.WsXpertGroup {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="wsdata", Namespace="http://schemas.datacontract.org/2004/07/WsService")]
    [System.SerializableAttribute()]
    public partial class wsdata : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string data {
            get {
                return this.dataField;
            }
            set {
                if ((object.ReferenceEquals(this.dataField, value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsXpertGroup.IWsXpertGroup")]
    public interface IWsXpertGroup {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsXpertGroup/SumData", ReplyAction="http://tempuri.org/IWsXpertGroup/SumDataResponse")]
        string[] SumData(Presentations.WsXpertGroup.wsdata wsdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsXpertGroup/SumData", ReplyAction="http://tempuri.org/IWsXpertGroup/SumDataResponse")]
        System.Threading.Tasks.Task<string[]> SumDataAsync(Presentations.WsXpertGroup.wsdata wsdata);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsXpertGroupChannel : Presentations.WsXpertGroup.IWsXpertGroup, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsXpertGroupClient : System.ServiceModel.ClientBase<Presentations.WsXpertGroup.IWsXpertGroup>, Presentations.WsXpertGroup.IWsXpertGroup {
        
        public WsXpertGroupClient() {
        }
        
        public WsXpertGroupClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsXpertGroupClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsXpertGroupClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsXpertGroupClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] SumData(Presentations.WsXpertGroup.wsdata wsdata) {
            return base.Channel.SumData(wsdata);
        }
        
        public System.Threading.Tasks.Task<string[]> SumDataAsync(Presentations.WsXpertGroup.wsdata wsdata) {
            return base.Channel.SumDataAsync(wsdata);
        }
    }
}
